application: nekofier
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/ico/favicon\.ico
  upload: favicon\.ico

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- remote_api: on
